# Generated by Django 4.2.2 on 2023-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_description_txt',
            field=models.CharField(blank=True, max_length=200000, null=True),
        ),
        migrations.DeleteModel(
            name='QuestionDescription',
        ),
    ]
