# Generated by Django 4.2.2 on 2023-07-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Övning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fråga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2500)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('Övning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fråga', to='övning_app.övning')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=15)),
                ('text', models.CharField(blank=True, max_length=1500)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('correct_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativ', to='övning_app.fråga')),
            ],
        ),
    ]
