# Generated by Django 4.2.2 on 2023-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('övning_app', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('all_questions_answered', models.ManyToManyField(blank=True, related_name='all_questions_answered', to='base.question')),
                ('besvarade_frågor', models.ManyToManyField(blank=True, related_name='besvarade_frågor', to='övning_app.fråga')),
                ('completed_provläge_prov', models.ManyToManyField(blank=True, related_name='completed_provläge', to='base.prov')),
                ('completed_provläge_quiz', models.ManyToManyField(blank=True, related_name='completed_provläge_quiz', to='base.prov')),
                ('completed_questions', models.ManyToManyField(blank=True, related_name='completed_questions', to='base.question')),
                ('completed_quizzes', models.ManyToManyField(blank=True, related_name='completed_quizzes', to='base.quiz')),
                ('correct_questions_answered', models.ManyToManyField(blank=True, related_name='correct_questions_answered', to='base.question')),
                ('done_quiz', models.ManyToManyField(blank=True, related_name='done_quiz', to='base.quiz')),
                ('gjorda_övningar', models.ManyToManyField(blank=True, related_name='gjorda_övningar', to='övning_app.övning')),
                ('pending_provs', models.ManyToManyField(blank=True, related_name='pending_provs', to='base.prov')),
                ('pending_quizzes', models.ManyToManyField(blank=True, related_name='pending_quizzes', to='base.quiz')),
                ('påbörjade_övningar', models.ManyToManyField(blank=True, related_name='påbörjade_övningar', to='övning_app.övning')),
                ('your_choise', models.ManyToManyField(blank=True, related_name='your_choise', to='base.choise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
